multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/gpfs0/jdubi/users/kasirer/Python-3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "dots_array.py", line 1307, in runSingleSimulation
    currentMap=currentMap, basePath=basePath, resume=resume)
  File "dots_array.py", line 941, in calcIV
    self.calcCurrent(tStep/10)
  File "dots_array.py", line 799, in calcCurrent
    dt = self.executeLeapingStep(printState=print_stats)
  File "dots_array.py", line 767, in executeLeapingStep
    dt = self.dotArray.getLeapingTimeInterval()
  File "dots_array.py", line 545, in getLeapingTimeInterval
    tau1 = np.min(smallestChange[changeAvg > 0]/changeAvg[changeAvg > 0])
  File "/gpfs0/jdubi/users/kasirer/home/.local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2618, in amin
    initial=initial)
  File "/gpfs0/jdubi/users/kasirer/home/.local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dots_array.py", line 1760, in <module>
    checkSteadyState=False, superconducting=sc, gap=gap, leaping=leaping)
  File "dots_array.py", line 1405, in runFullSimulation
    result = res.get()
  File "/gpfs0/jdubi/users/kasirer/Python-3.7/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: zero-size array to reduction operation minimum which has no identity
