
python3 dots_array.py -M 5 -N 5 --vmin 0 --vmax 5 --vstep 0.01 --vr 0 --vg-avg 0 --vg-std 0 --c-avg 1 --c-std 0 --cg-avg 10 --cg-std 0 --r-avg 10 --r-std 9 --rg-avg 1000 --rg-std 0 --repeats 20 --n-avg 0 --n-std 0 --q-avg 0 --q-std 0 --distribution uniform --custom-rh "" --custom-rv "" --file-name uniform_disorder_5_5 -o 2D_square_arrays_with_current_map  --current-map

Traceback (most recent call last):
  File "dots_array.py", line 952, in <module>
    printState=False, useGraph=use_graph, fastRelaxation=fast_relaxation, currentMap=current_map)
  File "dots_array.py", line 722, in runFullSimulation
    saveCurrentMaps(avgImaps,V, basePath + "_Imap")
  File "dots_array.py", line 740, in saveCurrentMaps
    im_ani.save(path + '.mp4', writer=writer)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/animation.py", line 1174, in save
    writer.grab_frame(**savefig_kwargs)
  File "/usr/local/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/animation.py", line 232, in saving
    self.finish()
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/animation.py", line 358, in finish
    self.cleanup()
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/animation.py", line 395, in cleanup
    out, err = self._proc.communicate()
  File "/usr/local/anaconda3/lib/python3.7/subprocess.py", line 933, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/local/anaconda3/lib/python3.7/subprocess.py", line 1666, in _communicate
    selector.register(self.stdout, selectors.EVENT_READ)
  File "/usr/local/anaconda3/lib/python3.7/selectors.py", line 352, in register
    key = super().register(fileobj, events, data)
  File "/usr/local/anaconda3/lib/python3.7/selectors.py", line 238, in register
    key = SelectorKey(fileobj, self._fileobj_lookup(fileobj), events, data)
  File "/usr/local/anaconda3/lib/python3.7/selectors.py", line 225, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/anaconda3/lib/python3.7/selectors.py", line 40, in _fileobj_to_fd
    "{!r}".format(fileobj)) from None
ValueError: Invalid file object: <_io.BufferedReader name=37>
